### PR TITLE
Take dynamic values out of js compressor and fix a check

### LINKED ISSUE #1312: Incorrect warning alert when opening an event that has extras choices
When opening an event that has extras choices attached, one gets a warning alert with the following message: "Ditt valg til ekstra bestilling er ikke lenger gyldig! Velg et nytt." Happens when opening https://online.ntnu.no/events/197/kurs-med-knowit/ before registration is opened.

### PR DESCRIPTION
**Pull request by nixolas1**
Displayed a erroneous warning message when user wasn't attending event with extra choices.
Fixes #1312

### CODE REVIEW

File: files/static/js/events.js [hunk 1]
```diff
@@ -27,7 +27,7 @@ return {
             message = "Vennligst velg et alternativ for extra bestilling. (Over avmeldingsknappen)";
             Event.showFlashMessage(message, 'alert-warning')
         }
-        else if(all_extras.length >0 && jQuery.inArray(selected_extra, all_extras) == -1){
+        else if(all_extras.length >0 && selected_extra != "" && jQuery.inArray(selected_extra, all_extras) == -1){
```
Comment (melwil) [inline files/static/js/events.js]: !==
